### ISSUE TITLE
File-based configuration

### ISSUE THREAD

**Issue by VJftw** [VJftw/docker-registry-proxy#5]
In order to make Docker Registry Proxy/Kubelet Image Service/Providers/Verifiers configuration clearer and more readable, we should encourage/enforce configuration via files instead.

I'm currently in favour of ~HCL~ or YAML files for configuration. 

Choosing YAML, as HCL is a bit of a mess after being parsed in Viper.

Initial ideas for how configuration will look:
```yaml
---
# docker-registry-proxy.yaml
upstream_repository: https://gcr.io/foo-project
plugins: 
  auth_provider:
    upstream_static:
      name: static
  auth_verifier:
    gcpverifier:
      name: gcp-instanceidentitydocument
      config:
        project_ids:
          - my-foo-project
    awsverifier:
      name: aws-instanceidentitydocument
      config:
        account_ids:
           - 1234567890
upstream_authentication_service: upstream_static
```

```yaml
# kubelet-image-service.yaml

```
